### ISSUE TITLE
Component registration at the Administrator

### ISSUE THREAD

**Issue by jordi133** [scala-academy/performance-analysis#10]
Given the server is running
And I registered a component by doing a POST with {"componentId" : "TestComponent"} to /components on the Administrator port
When I do a HTTP GET to '/components' on the Administrator port
Then the response should have statuscode 200
And the content should be a list containing {"componentId" : "TestComponent"}

**Comment by jordi133** [comment]
A small start for the acceptance test has been made in ComponentRegistrationTest.scala

**Comment by effibennekers** [comment]
Is it a list containing _only_ {"componentId" : "TestComponent"}?

**Comment by jordi133** [comment]
Initially that would be sufficient I suppose. Given the componentId, additional details can be easily requested with a GET on '/components/<componentId>'. Expanding the data in the result of a GET to '/components' should be another user story.
