### ISSUE TITLE
Log Receiver should only support POST operations

### ISSUE THREAD

**Issue by jordi133** [scala-academy/performance-analysis#11]
Given the server is running
When I do a HTTP GET to '/' on the LogReceiver port
Then the response should have statuscode 405

**Comment by jordi133** [comment]
A small start for the acceptance test has been made in ComponentRegistrationTest.scala

**Comment by jordi133** [comment]
Acceptance test should be implemented in LogSubmissionTest.scala. Keep in mind that unit testing for the HTTP routes should be done in LogReceiverSpec similar to AdministratorSpec

**Comment by ruud** [comment]
I will try to pick this one up

**Comment by jordi133** [comment]
Please add both unit tests and integration (acceptance) tests
