### ISSUE TITLE
Single log line posted

### ISSUE THREAD

**Issue by jordi133** [scala-academy/performance-analysis#16]
Given the server is running
I registered a component with id "parsingConfiguredComponent" and a metric {"regex" : "some action took (\d+) ms", "metric-key" : "a-numerical-metric"}
I do a POST with {"log" : "some action took 101 ms"} to /components/parsingConfiguredComponent/logs on the LogReceiver port 
the response should have statuscode 202

**Comment by jordi133** [comment]
Acceptance test should be implemented in LogSubmissionTest.java

In addition to the 202 statuscode being returned, eventually the numerical value should be stored inside the API for future analysis.

**Comment by effibennekers** [comment]
shouldnt the url be /components/parsingConfiguredComponent/logs?

**Comment by ruud** [comment]
#58 is dependent

**Comment by geerdink** [comment]
When checking a regex, pick the first hit in a log line.
E.g. "bla bla 100 ms bla bla bla 200 ms bla bla" with regex "(/d ms)" only gets "100 ms" as a result to parse.
