### ISSUE TITLE
Parsed metrics obtainable through Administrator

### ISSUE THREAD

**Issue by jordi133** [scala-academy/performance-analysis#17]
Given the server is running and I registered component "logsObtainableComp"
And I posted a logline "some action took 101 seconds" on this component
When I do a GET to /components/logsObtainableComp/logs
Then the result should have statuscode 200
And the content should contain "some action took 101 seconds"

Given the server is running and I registered component "logsObtainableComp" with a metric with metric-key "a-numerical-metric"
And I posted a logline "some action took 101 seconds" to the component
And that logline is parsed by the metric "a-numerical-metric"
When I do a GET to /components/logsObtainableComp/metrics/a-numerical-metric
Then the result should have statuscode 200
And the content should contain "101"

**Comment by effibennekers** [comment]
The first will return the logline, the second the regular expression applied to the logline for this metric.

**Comment by jwvl** [comment]
Dear all,
I have still not been able to make a lot of progress on this story and will not be able to attend the next two sessions because of a holiday. Since I do not want to hold back the project I propose someone else take it over. I will do my best to catch up with things in two weeks' time.

**Comment by ruud** [comment]
I will pick it up

**Comment by ruud** [comment]
Should getting (via administrator) of the logline be delegated to the LogReceiverActor?

**Comment by jordi133** [comment]
Good question. What do you think are the pro's and con's of that? And what are alternatives?

**Comment by ruud** [comment]
I implemented it in such a way that the LogParserActor is holding the logLines
