### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by TimSoethout** [scala-academy/performance-analysis#31]
Create a separate folder in the src-folder (src/perf) and create a basic gatling project in there. Modify build.sbt to allow the gatling tests to be run easily from sbt.

**Comment by TimSoethout** [comment]
Would it be acceptable if the gatling tests are in the `/it/` folder?

**Comment by TimSoethout** [comment]
@Seetaramayya  These two lines (in build.sbt) seem to work in your example project:

```
scalaSource in Gatling := baseDirectory.value / "src/perf"
fullClasspath in Gatling += crossTarget.value / "gatling-classes/"
```

then `gatling:test` runs!
Haven't tried yet for this project.

**Comment by Seetaramayya** [comment]
@TimSoethout thanks, I'll check it. If we can tweak class path then it should work.
