### ISSUE TITLE
Alerting Rules

### ISSUE THREAD

**Issue by jordi133** [scala-academy/performance-analysis#38]
When logs for a component are parsed, metrics are gathered. An Alerting Rule (which is defined per component&rule) is meant to trigger an action when a specific metric breaks a given rule. One of such rules could be: "response time should always be less than 2000 ms".

To finalize this functionality, please automate and implement the following acceptance criteria

Given the server is running and I registered component "logsObtainableComp" with a metric with metric-key "a-numerical-metric"
When I do a POST to /components/logsObtainableComp/metrics/a-numerical-metric/alerting-rules with payload {"threshold": {"max": "2000 ms"}, "action": {"url": "dummy-action"}}
Then the result should have statuscode 201

Given the server is running and I registered component "logsObtainableComp" with a metric with metric-key "a-numerical-metric"
And I resistered a threshold on "a-numerical-metric" with max "2000 ms"
When I do a POST to /components/logsObtainableComp/logs with a payload that triggers the registered threashold
Then the result should have statuscode 200
And the action related to the threshold should be triggered

Given the server is running and I registered component "logsObtainableComp" with a metric with metric-key "a-numerical-metric"
And I resistered a threshold on "a-numerical-metric" with max "2000 ms"
When I do a POST to /components/logsObtainableComp/logs with a payload that does not trigger the registered threshold
Then the result should have statuscode 200
And the action related to the threshold should not be triggered

**Comment by effibennekers** [comment]
For the implementers: Think about how the triggering could be tested in your integration test
