### ISSUE TITLE
Adjust IntegrationTestBase

### ISSUE THREAD

**Issue by geerdink** [scala-academy/performance-analysis#62]
Use the new twitterFutures from Ruud

**Comment by TimSoethout** [comment]
1. Invoking futureValue, to obtain a futures result within a specified or implicit time period, like this:

`assert(result.futureValue === 7)`

http://www.artima.com/docs-scalatest-2.0.M5/org/scalatest/concurrent/Futures.html

**Comment by gvr** [comment]
Lead to pull request #65
