### ISSUE TITLE
Refactor Protocol

### ISSUE THREAD

**Issue by jordi133** [scala-academy/performance-analysis#79]
The protocol trait is getting a bit too big, let's refactor this. Proposal is to at least separate the directly server related messages from the messages that are used between actors.

**Comment by jwvl** [comment]
I'll try to tackle this one to get back in shape after my holidays ;)

**Comment by jwvl** [comment]
We were having some strange trouble merging my commits with develop. I finally decided to just start a new branch. I will follow @Seetaramayya's suggestion and refactor Protocol into several functional parts e.g. LogParserProtocol, AlertProtocol etc. etc.
